# -*- coding: utf-8 -*-
"""Training_yolov5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zG-cuW1E4ZVt89VlPJPnqHXsD7WwlTlh
"""

import os
os.chdir('/content/drive/MyDrive/License_plate_Yolo')

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd yolov5
# pip install -r requirements.txt

os.chdir('yolov5')

!python train.py --data data.yaml --cfg yolov5s.yaml --batch-size 8 --name Model --epochs 100

!python /content/drive/MyDrive/License_plate_Yolo/yolov5/export.py --weights /content/drive/MyDrive/License_plate_Yolo/yolov5/runs/train/Model/weights/best.pt --include torchscript onnx

